name: 🔨 Build Mudlet - PR (windows)
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '**.md'

permissions:
  contents: read

jobs:
  compile-mudlet:
    name: ${{matrix.buildname}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildname:
          - 'windows64'
    steps:
    - run: echo "FORK ONLY trivial build stand-in"
