name: 🔨 Build Mudlet - PR
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '**.md'

jobs:
  compile-mudlet:
    name: ${{matrix.buildname}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildname:
          - 'ubuntu / gcc / lua tests + leak detection'
          - 'macos (x86_64)'
          - 'macos (arm64) / c++, lua tests'
    steps:
    - run: echo "FORK ONLY trivial build stand-in"
